//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public Association()
        {
            this.AssocitationCategories = new HashSet<AssocitationCategory>();
            this.EventAssociations = new HashSet<EventAssociation>();
            this.Events = new HashSet<Event>();
        }
    
        public System.Guid Id { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifieldDate { get; set; }
        public string Logo { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<AssocitationCategory> AssocitationCategories { get; set; }
        public virtual ICollection<EventAssociation> EventAssociations { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
