//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Associations = new HashSet<Association>();
            this.Events = new HashSet<Event>();
            this.Organizers = new HashSet<Organizer>();
            this.Persons = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public string Coordinates { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifieldDate { get; set; }
    
        public virtual ICollection<Association> Associations { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Organizer> Organizers { get; set; }
        public virtual ICollection<Person> Persons { get; set; }
    }
}
