//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events1
    {
        public System.Guid Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public string PackagePath { get; set; }
        public Nullable<int> ServerId { get; set; }
        public Nullable<int> TemplateId { get; set; }
    }
}
