//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAsset
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
