//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAssociation
    {
        public System.Guid Id { get; set; }
        public System.Guid EventId { get; set; }
        public System.Guid AssociationId { get; set; }
        public System.DateTime LastModifieldDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Association Association { get; set; }
        public virtual Event Event { get; set; }
    }
}
