//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events2
    {
        public System.Guid Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string FromRole { get; set; }
        public string ToRole { get; set; }
        public string Type { get; set; }
        public string RowId { get; set; }
        public string DateTime { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string ReponseTime { get; set; }
    }
}
