//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public int TableNameId { get; set; }
        public int TableNameRowId { get; set; }
        public byte Status { get; set; }
        public string Provider { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifieldDate { get; set; }
    }
}
